version: '3.8'

services:
  mysql:
    container_name: mysqldb
    image: mysql:latest
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: todo4
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: